10.2 
Importing Classes Account and Decimal

In [1]:
from accounts import Account
from decimal import Decimal


Importing Classes Account and Decimal

In [4]:
value = Decimal('12.34')
account1 = Account('John Green', Decimal('50.00'))

Getting an Account’s Name and Balance

In [25]:
print(account1.name)
print(account1.balance)

John Green
75.53


Depositing Money into an Account

In [24]:
account1.deposit(Decimal('25.53'))
print(account1.balance)

75.53


Testing method withdraw

In [30]:
from accounts import Account
from decimal import Decimal

In [31]:
account1 = Account('John Green', Decimal('50.00'))
account1.withdraw(Decimal('20.00'))
print(account1.balance)

AttributeError: 'Account' object has no attribute 'withdraw'

10.3
Controlling Access to Attributes - valid balance

In [32]:
account1 = Account('John Green', Decimal('50.00'))
print(account1.balance)

50.00


Controlling Access to Attributes - invalid balance

In [33]:
account1 = Account('John Green', Decimal('-1000.00'))
print(account1.balance)

ValueError: Initial balance must be >= to 0.00.

10.4 Import Class Time

In [34]:
from timewithproperties import Time

Creating and displaying a Time Object

In [37]:
wake_up = Time(hour=6, minute=30)
print(wake_up)

6:30:00 AM


Getting an Attribute Via a Property

In [39]:
print(wake_up.hour)

6


Setting the Time

In [42]:
wake_up.set_time(hour=7, minute=45)
print(wake_up)

7:45:00 AM


Setting an Attribute via a Property

In [43]:
wake_up.hour = 6
wake_up

Time(hour=6, minute=45, second=0)

Attempting to Set an Invalid Value

In [44]:
wake_up.hour = 100

ValueError: Hour (100) must be 0-23

In [39]:
from timewithproperties import Time

In [40]:
t = Time()

In [41]:
t

Time(hour=0, minute=0, second=0)

In [46]:
t.time = (12, 30, 45)

In [51]:
t

Time(hour=12, minute=30, second=45)

In [56]:
t.time

(12, 30, 45)

10.5 Demonstrating “Private” Attributes

In [57]:
from private import PrivateClass

In [58]:
my_object = PrivateClass()

In [59]:
my_object.public_data

'public'

In [60]:
my_object.__private_data

AttributeError: 'PrivateClass' object has no attribute '__private_data'

10.6 Test-Driving Classes Card and DeckOfCards

In [ ]:
from deck import DeckOfCards

In [ ]:
deck_of_cards = DeckOfCards()

In [ ]:
print(deck_of_cards)

Ace of Hearts      2 of Hearts        3 of Hearts        4 of Hearts        
5 of Hearts        6 of Hearts        7 of Hearts        8 of Hearts        
9 of Hearts        10 of Hearts       Jack of Hearts     Queen of Hearts    
King of Hearts     Ace of Diamonds    2 of Diamonds      3 of Diamonds      
4 of Diamonds      5 of Diamonds      6 of Diamonds      7 of Diamonds      
8 of Diamonds      9 of Diamonds      10 of Diamonds     Jack of Diamonds   
Queen of Diamonds  King of Diamonds   Ace of Clubs       2 of Clubs         
3 of Clubs         4 of Clubs         5 of Clubs         6 of Clubs         
7 of Clubs         8 of Clubs         9 of Clubs         10 of Clubs        
Jack of Clubs      Queen of Clubs     King of Clubs      Ace of Spades      
2 of Spades        3 of Spades        4 of Spades        5 of Spades        
6 of Spades        7 of Spades        8 of Spades        9 of Spades        
10 of Spades       Jack of Spades     Queen of Spades    King of Spades     

In [ ]:
deck_of_cards.shuffle()

In [ ]:
print(deck_of_cards)

Jack of Diamonds   6 of Spades        2 of Hearts        9 of Clubs         
10 of Hearts       6 of Hearts        Queen of Clubs     King of Hearts     
3 of Spades        Ace of Hearts      2 of Clubs         4 of Diamonds      
Queen of Spades    9 of Spades        Jack of Clubs      4 of Clubs         
2 of Spades        5 of Diamonds      King of Spades     King of Clubs      
5 of Spades        3 of Clubs         Ace of Diamonds    7 of Hearts        
6 of Clubs         5 of Hearts        Jack of Hearts     10 of Clubs        
8 of Clubs         7 of Clubs         10 of Diamonds     9 of Diamonds      
8 of Spades        Jack of Spades     10 of Spades       7 of Spades        
2 of Diamonds      3 of Hearts        9 of Hearts        3 of Diamonds      
Queen of Diamonds  7 of Diamonds      8 of Diamonds      Queen of Hearts    
6 of Diamonds      Ace of Clubs       Ace of Spades      5 of Clubs         
8 of Hearts        King of Diamonds   4 of Hearts        4 of Spades        

In [ ]:
deck_of_cards.deal_card()

Card(face='Jack', suit='Diamonds')

In [ ]:
card = deck_of_cards.deal_card()

In [ ]:
str(card)

'6 of Spades'

In [ ]:
card.image_name

'6_of_Spades.png'

Displaying Card Images with Matplotlib

In [ ]:
from deck import DeckOfCards

In [ ]:
deck_of_cards = DeckOfCards()

In [ ]:
%matplotlib

Using matplotlib backend: QtAgg


In [ ]:
from pathlib import Path

In [ ]:
path = Path('.').joinpath('card_images')

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import matplotlib.image as mpimg

In [61]:
figure, axes_list = plt.subplots(nrows=4, ncols=13)

# added next two statements to increase figure size in notebook
figure.set_figwidth(16)
figure.set_figheight(9)

for axes in axes_list.ravel():
    axes.get_xaxis().set_visible(False)
    axes.get_yaxis().set_visible(False)
    image_name = deck_of_cards.deal_card().image_name
    img = mpimg.imread(str(path.joinpath(image_name).resolve()))
    axes.imshow(img)

figure.tight_layout()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\klg56\\OneDrive\\Documents\\datafun-07-ml\\card_images\\5_of_Hearts.png'

10.8 Testing Class CommissionEmployee

In [63]:
from commisionemployee import CommissionEmployee

In [64]:
from decimal import Decimal

In [65]:
c = CommissionEmployee('Sue', 'Jones', '333-33-3333', Decimal('10000.00'), Decimal('0.06'))

In [66]:
c

CommissionEmployee: Sue Jones
social security number: 333-33-3333
gross sales: 10000.00
commission rate: 0.06

In [67]:
print(f'{c.earnings():,.2f}')

600.00


In [68]:
c.gross_sales = Decimal('20000.00')

In [69]:
c.commission_rate = Decimal('0.1')

In [70]:
print(f'{c.earnings():,.2f}')

2,000.00


10.16 Linear Relationships

In [71]:
c = lambda f: 5 / 9 * (f - 32)

In [72]:
temps = [(f, c(f)) for f in range(0, 101, 10)]

In [73]:
import pandas as pd

In [74]:
temps_df = pd.DataFrame(temps, columns=['Fahrenheit', 'Celsius'])

In [76]:
axes = temps_df.plot(x='Fahrenheit', y='Celsius', style='.-')
y_label = axes.set_ylabel('Celsius')

Loading the Average High Temperatures into a DataFrame

In [78]:
nyc = pd.read_csv('ave_hi_nyc_jan_1895-2018.csv')

In [79]:
nyc.head()

Date  Value  Anomaly
0  189501   34.2     -3.2
1  189601   34.7     -2.7
2  189701   35.5     -1.9
3  189801   39.6      2.2
4  189901   36.4     -1.0

In [80]:
nyc.tail()

Date  Value  Anomaly
119  201401   35.5     -1.9
120  201501   36.1     -1.3
121  201601   40.8      3.4
122  201701   42.8      5.4
123  201801   38.7      1.3

In [81]:
nyc.columns = ['Date', 'Temperature', 'Anomaly']

In [82]:
nyc.head(3)

Date  Temperature  Anomaly
0  189501         34.2     -3.2
1  189601         34.7     -2.7
2  189701         35.5     -1.9

In [83]:
nyc.Date.dtype

dtype('int64')

In [84]:
nyc.Date = nyc.Date.floordiv(100)

In [85]:
nyc.head(3)

Date  Temperature  Anomaly
0  1895         34.2     -3.2
1  1896         34.7     -2.7
2  1897         35.5     -1.9

In [88]:
nyc.Temperature.describe()

count    124.000000
mean      37.595161
std        4.539848
min       26.100000
25%       34.575000
50%       37.600000
75%       40.600000
max       47.600000
Name: Temperature, dtype: float64

Forecasting Future January Average High Temperatures

In [89]:
from scipy import stats

In [90]:
linear_regression = stats.linregress(x=nyc.Date, y=nyc.Temperature)

In [91]:
linear_regression.slope

0.014771361132966163

In [92]:
linear_regression.intercept

8.694993233674289

In [93]:
linear_regression.slope * 2019 + linear_regression.intercept

38.51837136113297

In [94]:
linear_regression.slope * 1890 + linear_regression.intercept

36.612865774980335

In [95]:
import seaborn as sns

In [96]:
sns.set_style('whitegrid')
axes = sns.regplot(x=nyc.Date, y=nyc.Temperature)

In [97]:
axes.set_ylim(10, 70)

(10.0, 70.0)

15.2 Classification with k-nearest neighbors and the digits dataset

In [98]:
from sklearn.datasets import load_digits

In [99]:
digits = load_digits()

In [100]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [101]:
digits.target[::100]

array([0, 4, 1, 7, 4, 8, 2, 2, 4, 4, 1, 9, 7, 3, 2, 1, 2, 5])

In [102]:
digits.data.shape

(1797, 64)

In [103]:
digits.target.shape

(1797,)

In [104]:
digits.images[13]

array([[ 0.,  2.,  9., 15., 14.,  9.,  3.,  0.],
       [ 0.,  4., 13.,  8.,  9., 16.,  8.,  0.],
       [ 0.,  0.,  0.,  6., 14., 15.,  3.,  0.],
       [ 0.,  0.,  0., 11., 14.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  2., 15., 11.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2., 15.,  4.,  0.],
       [ 0.,  1.,  5.,  6., 13., 16.,  6.,  0.],
       [ 0.,  2., 12., 12., 13., 11.,  0.,  0.]])

In [105]:
digits.data[13]

array([ 0.,  2.,  9., 15., 14.,  9.,  3.,  0.,  0.,  4., 13.,  8.,  9.,
       16.,  8.,  0.,  0.,  0.,  0.,  6., 14., 15.,  3.,  0.,  0.,  0.,
        0., 11., 14.,  2.,  0.,  0.,  0.,  0.,  0.,  2., 15., 11.,  0.,
        0.,  0.,  0.,  0.,  0.,  2., 15.,  4.,  0.,  0.,  1.,  5.,  6.,
       13., 16.,  6.,  0.,  0.,  2., 12., 12., 13., 11.,  0.,  0.])

In [106]:
import matplotlib.pyplot as plt

In [111]:
figure, axes = plt.subplots(nrows=4, ncols=6, figsize=(6, 4))

### Displaying Each Image and Removing the Axes Labels 

for item in zip(axes.ravel(), digits.images, digits.target):
    axes, image, target = item
    axes.imshow(image, cmap=plt.cm.gray_r)
    axes.set_xticks([])  # remove x-axis tick marks
    axes.set_yticks([])  # remove y-axis tick marks
    axes.set_title(target)
plt.tight_layout()  

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, random_state=11)

In [114]:
X_train.shape

(1347, 64)

In [115]:
X_test.shape

(450, 64)

In [116]:
from sklearn.neighbors import KNeighborsClassifier

In [117]:
knn = KNeighborsClassifier()

In [118]:
knn.fit(X=X_train, y=y_train)

KNeighborsClassifier()

In [119]:
predicted = knn.predict(X=X_test)

In [120]:
expected = y_test

In [121]:
predicted[:20]

array([0, 4, 9, 9, 3, 1, 4, 1, 5, 0, 4, 9, 4, 1, 5, 3, 3, 8, 5, 6])

In [122]:
expected[:20]

array([0, 4, 9, 9, 3, 1, 4, 1, 5, 0, 4, 9, 4, 1, 5, 3, 3, 8, 3, 6])

In [123]:
wrong = [(p, e) for (p, e) in zip(predicted, expected) if p != e]

In [124]:
wrong

[(5, 3),
 (8, 9),
 (4, 9),
 (7, 3),
 (7, 4),
 (2, 8),
 (9, 8),
 (3, 8),
 (3, 8),
 (1, 8)]

15.4 Time Series and Simple Linear Regression

In [125]:
import pandas as pd

In [126]:
nyc = pd.read_csv('ave_hi_nyc_jan_1895-2018.csv')

In [127]:
nyc.columns = ['Date', 'Temperature', 'Anomaly']

In [128]:
nyc.Date = nyc.Date.floordiv(100)

In [129]:
nyc.head(3)

Date  Temperature  Anomaly
0  1895         34.2     -3.2
1  1896         34.7     -2.7
2  1897         35.5     -1.9

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
X_train, X_test, y_train, y_test = train_test_split(nyc.Date.values.reshape(-1, 1), nyc.Temperature.values, random_state=11)

In [132]:
X_train.shape

(93, 1)

In [133]:
X_test.shape

(31, 1)

In [134]:
from sklearn.linear_model import LinearRegression

In [135]:
linear_regression = LinearRegression()

In [136]:
linear_regression.fit(X=X_train, y=y_train)

LinearRegression()

In [137]:
linear_regression.coef_

array([0.01939167])

In [138]:
linear_regression.intercept_

-0.30779820252656265

In [139]:
predicted = linear_regression.predict(X_test)

In [140]:
expected = y_test

In [141]:
for p, e in zip(predicted[::5], expected[::5]):
    print(f'predicted: {p:.2f}, expected: {e:.2f}')

predicted: 37.86, expected: 31.70
predicted: 38.69, expected: 34.80
predicted: 37.00, expected: 39.40
predicted: 37.25, expected: 45.70
predicted: 38.05, expected: 32.30
predicted: 37.64, expected: 33.80
predicted: 36.94, expected: 39.70


In [142]:
predict = (lambda x: linear_regression.coef_ * x + linear_regression.intercept_)

In [143]:
predict(2019)

array([38.84399018])

In [144]:
predict(1890)

array([36.34246432])

In [145]:
import seaborn as sns

In [146]:
axes = sns.scatterplot(data=nyc, x='Date', y='Temperature',
    hue='Temperature', palette='winter', legend=False)

In [147]:
axes.set_ylim(10, 70)

(10.0, 70.0)

In [158]:
import numpy as np
import matplotlib.pyplot as plt

In [160]:
x = np.array([min(nyc.Date.values), max(nyc.Date.values)])
y = predict(x)
line = plt.plot(x, y)